name: Tests et déploiement

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configuration Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configuration du projet
      run: |
        python scripts/setup.py
    
    - name: Tests (si disponibles)
      run: |
        echo "Tests à implémenter"
        # python -m pytest tests/
    
    - name: Vérification de la structure
      run: |
        python -c "from config import *; create_directories(); print('Structure OK')"
